# kind-cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8880
        protocol: TCP
      - containerPort: 443
        hostPort: 44443
        protocol: TCP

  - role: worker
  - role: worker
##kind create cluster --name practice --config kind-cluster.yaml
##kind delete cluster --name practice here practice is the name of the cluster and kindcluster.yml is the name of the file from which the cluster is created.  
